name: Acme-Tests
version: 0.01
abstract: How much do you Know ?
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Spiffy: 0
  List::Util: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
